// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hychyqtqrmlykoppbkvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5Y2h5cXRxcm1seWtvcHBia3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDQ3NjksImV4cCI6MjA3MzE4MDc2OX0.5MH4UatuzUAFBawlh4VVa-NOJb8ovxEWM6BYe8ct6Xc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});